ROOT_DIR=../..

LIB=libbio.a
OBJ=\
	bbuffered.o\
	bfildes.o\
	bflush.o\
	bgetc.o\
	bgetrune.o\
	bgetd.o\
	binit.o\
	boffset.o\
	bprint.o\
	bputc.o\
	bputrune.o\
	brdline.o\
	brdstr.o\
	bread.o\
	bseek.o\
	bvprint.o\
	bwrite.o

include $(ROOT_DIR)/make/lib.mk
