ROOT_DIR=../..

LIB=libmemdraw.a
OBJ=\
	alloc.o\
	alloc-stub.o\
	arc.o\
	cload.o\
	cload-stub.o\
	cmap.o\
	cread.o\
	draw.o\
	draw-stub.o\
	ellipse.o\
	fillpoly.o\
	hwdraw.o\
	iprint.o\
	line.o\
	load.o\
	load-stub.o\
	openmemsubfont.o\
	poly.o\
	read.o\
	string.o\
	subfont.o\
	unload.o\
	unload-stub.o\
	write.o

include $(ROOT_DIR)/make/lib.mk
