ROOT_DIR=../..

LIB=lib9pclient.a
OBJ=\
	access.o\
	auth.o\
	close.o\
	create.o\
	dirread.o\
	fs.o\
	ns.o\
	open.o\
	openfd.o\
	print.o\
	read.o\
	remove.o\
	seek.o\
	stat.o\
	walk.o\
	write.o\
	wstat.o

include $(ROOT_DIR)/make/lib.mk
