ROOT_DIR=../../..

OBJ=\
	acme.o\
	addr.o\
	buff.o\
	cols.o\
	disk.o\
	ecmd.o\
	edit.o\
	elog.o\
	exec.o\
	file.o\
	fsys.o\
	logf.o\
	look.o\
	regx.o\
	rows.o\
	scrl.o\
	text.o\
	time.o\
	util.o\
	wind.o\
	xfid.o\
	dat.o
BIN=acme

include $(ROOT_DIR)/make/bin.mk
