ROOT_DIR=../../..

OBJ=\
	sam.o\
	address.o\
	buff.o\
	cmd.o\
	disk.o\
	error.o\
	file.o\
	io.o\
	list.o\
	mesg.o\
	moveto.o\
	multi.o\
	rasp.o\
	regexp.o\
	shell.o\
	string.o\
	sys.o\
	unix.o\
	util.o\
	xec.o
BIN=sam

include $(ROOT_DIR)/make/bin.mk
