ROOT_DIR=../..

LIB=libmemlayer.a
OBJ=\
	draw.o\
	lalloc.o\
	layerop.o\
	ldelete.o\
	lhide.o\
	line.o\
	load.o\
	lorigin.o\
	lsetrefresh.o\
	ltofront.o\
	ltorear.o\
	unload.o

include $(ROOT_DIR)/make/lib.mk
