ROOT_DIR=../..

LIB=libauth.a
OBJ=\
	amount_getkey.o\
	attr.o\
	auth_attr.o\
	auth_challenge.o\
	auth_getkey.o\
	auth_getuserpasswd.o\
	auth_proxy.o\
	auth_respond.o\
	auth_rpc.o\
	auth_userpasswd.o\
	fsamount.o\
	nsamount.o

include $(ROOT_DIR)/make/lib.mk
